"""add debit_standard with many-to-many

Revision ID: 0d096d0c4d98
Revises: ee1a58033dfd
Create Date: 2026-01-23 14:34:44.484365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d096d0c4d98'
down_revision: Union[str, Sequence[str], None] = 'ee1a58033dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_standard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fluid_type', sa.String(), nullable=False),
    sa.Column('debit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debit_standard_association',
    sa.Column('debit_standard_id', sa.Integer(), nullable=False),
    sa.Column('diameter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['debit_standard_id'], ['debit_standard.id'], ),
    sa.ForeignKeyConstraint(['diameter_id'], ['standard_casing_diameter.id'], ),
    sa.PrimaryKeyConstraint('debit_standard_id', 'diameter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debit_standard_association')
    op.drop_table('debit_standard')
    # ### end Alembic commands ###
