"""add column coupling diameter to casing

Revision ID: 1242256abe68
Revises: 27b6dfca0ba6
Create Date: 2026-01-21 13:56:22.069026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1242256abe68'
down_revision: Union[str, Sequence[str], None] = '27b6dfca0ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_casing_diameter', sa.Column('coupling_diameter', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_casing_diameter', 'coupling_diameter')
    # ### end Alembic commands ###
