"""add bit table standard

Revision ID: 41293a2f0fca
Revises: 51d8415e2bef
Create Date: 2026-01-21 00:25:33.718320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41293a2f0fca'
down_revision: Union[str, Sequence[str], None] = '51d8415e2bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bit')
    # ### end Alembic commands ###
