"""seed gost standard data

Revision ID: 51d8415e2bef
Revises: f6feb1628d17
Create Date: 2026-01-20 20:27:20.165266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d8415e2bef'
down_revision: Union[str, Sequence[str], None] = 'f6feb1628d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            'standard_casing_diameter',
            sa.column('id', sa.Integer),
            sa.column('diameter', sa.Numeric)
        ),
        [
            {'id': 1, 'diameter': 114},
            {'id': 2, 'diameter': 127},
            {'id': 3, 'diameter': 140},
            {'id': 4, 'diameter': 146},
            {'id': 5, 'diameter': 168},
            {'id': 6, 'diameter': 178},
            {'id': 7, 'diameter': 194},
            {'id': 8, 'diameter': 219},
            {'id': 9, 'diameter': 245},
            {'id': 10, 'diameter': 273},
            {'id': 11, 'diameter': 299},
            {'id': 12, 'diameter': 324},
            {'id': 13, 'diameter': 340},
            {'id': 14, 'diameter': 351},
            {'id': 15, 'diameter': 377},
            {'id': 16, 'diameter': 406},
            {'id': 17, 'diameter': 426},
            {'id': 18, 'diameter': 473},
            {'id': 19, 'diameter': 508}
        ]
    )

    op.bulk_insert(
        sa.table(
            'wall_thickness',
            sa.column('id', sa.Integer),
            sa.column('thickness', sa.Float),
            sa.column('diameter_id', sa.Numeric)
        ),

        [
        #Diameter 114
            {'id': 1, 'thickness': 5.2, 'diameter_id': 1},
            {'id': 2, 'thickness': 5.7, 'diameter_id': 1},
            {'id': 3, 'thickness': 6.4, 'diameter_id': 1},
            {'id': 4, 'thickness': 7.4, 'diameter_id': 1},
            {'id': 5, 'thickness': 8.6, 'diameter_id': 1},
            {'id': 6, 'thickness': 10.2, 'diameter_id': 1},

        #Diameter 127
            {'id': 7, 'thickness': 5.6, 'diameter_id': 2},
            {'id': 8, 'thickness': 6.4, 'diameter_id': 2},
            {'id': 9, 'thickness': 7.5, 'diameter_id': 2},
            {'id': 10, 'thickness': 9.2, 'diameter_id': 2},
            {'id': 11, 'thickness': 10.2, 'diameter_id': 2},

        # Diameter 140
            {'id': 12, 'thickness': 6.2, 'diameter_id': 3},
            {'id': 13, 'thickness': 7.0, 'diameter_id': 3},
            {'id': 14, 'thickness': 7.7, 'diameter_id': 3},
            {'id': 15, 'thickness': 9.2, 'diameter_id': 3},
            {'id': 16, 'thickness': 10.5, 'diameter_id': 3},

        # Diameter 146
            {'id': 17, 'thickness': 6.5, 'diameter_id': 4},
            {'id': 18, 'thickness': 7, 'diameter_id': 4},
            {'id': 19, 'thickness': 7.7, 'diameter_id': 4},
            {'id': 20, 'thickness': 8.5, 'diameter_id': 4},
            {'id': 21, 'thickness': 9.5, 'diameter_id': 4},
            {'id': 22, 'thickness': 10.7, 'diameter_id': 4},

        #Diameter 168
            {'id': 23, 'thickness': 7.3, 'diameter_id': 5},
            {'id': 24, 'thickness': 8.0, 'diameter_id': 5},
            {'id': 25, 'thickness': 8.9, 'diameter_id': 5},
            {'id': 26, 'thickness': 10.6, 'diameter_id': 5},
            {'id': 27, 'thickness': 12.1, 'diameter_id': 5},

        #Diameter 178
            {'id': 28, 'thickness': 5.9, 'diameter_id': 6},
            {'id': 29, 'thickness': 6.9, 'diameter_id': 6},
            {'id': 30, 'thickness': 8.1, 'diameter_id': 6},
            {'id': 31, 'thickness': 9.2, 'diameter_id': 6},
            {'id': 32, 'thickness': 10.4, 'diameter_id': 6},
            {'id': 33, 'thickness': 11.5, 'diameter_id': 6},
            {'id': 34, 'thickness': 12.7, 'diameter_id': 6},
            {'id': 35, 'thickness': 13.7, 'diameter_id': 6},
            {'id': 36, 'thickness': 15.0, 'diameter_id': 6},

        #Diameter 194
            {'id': 37, 'thickness': 7.6, 'diameter_id': 7},
            {'id': 38, 'thickness': 8.3, 'diameter_id': 7},
            {'id': 39, 'thickness': 9.5, 'diameter_id': 7},
            {'id': 40, 'thickness': 10.9, 'diameter_id': 7},
            {'id': 41, 'thickness': 12.7, 'diameter_id': 7},
            {'id': 42, 'thickness': 15.1, 'diameter_id': 7},

        # Diameter 219
            {'id': 44, 'thickness': 6.7, 'diameter_id': 8},
            {'id': 45, 'thickness': 7.7, 'diameter_id': 8},
            {'id': 46, 'thickness': 8.9, 'diameter_id': 8},
            {'id': 47, 'thickness': 10.2, 'diameter_id': 8},
            {'id': 48, 'thickness': 11.4, 'diameter_id': 8},
            {'id': 49, 'thickness': 12.7, 'diameter_id': 8},
            {'id': 50, 'thickness': 14.2, 'diameter_id': 8},

        # Diameter 245
            {'id': 51, 'thickness': 7.9, 'diameter_id': 9},
            {'id': 52, 'thickness': 8.9, 'diameter_id': 9},
            {'id': 53, 'thickness': 10.0, 'diameter_id': 9},
            {'id': 54, 'thickness': 11.1, 'diameter_id': 9},
            {'id': 55, 'thickness': 12.0, 'diameter_id': 9},
            {'id': 56, 'thickness': 13.8, 'diameter_id': 9},
            {'id': 57, 'thickness': 15.9, 'diameter_id': 9},

        # Diameter 273
            {'id': 58, 'thickness': 7.1, 'diameter_id': 10},
            {'id': 59, 'thickness': 8.9, 'diameter_id': 10},
            {'id': 60, 'thickness': 10.2, 'diameter_id': 10},
            {'id': 61, 'thickness': 11.4, 'diameter_id': 10},
            {'id': 62, 'thickness': 12.6, 'diameter_id': 10},
            {'id': 63, 'thickness': 13.8, 'diameter_id': 10},
            {'id': 64, 'thickness': 15.1, 'diameter_id': 10},
            {'id': 65, 'thickness': 16.5, 'diameter_id': 10},

        # Diameter 299
            {'id': 66, 'thickness': 8.5, 'diameter_id': 11},
            {'id': 67, 'thickness': 9.5, 'diameter_id': 11},
            {'id': 68, 'thickness': 11.1, 'diameter_id': 11},
            {'id': 69, 'thickness': 12.4, 'diameter_id': 11},
            {'id': 70, 'thickness': 14.8, 'diameter_id': 11},

        # Diameter 324
            {'id': 71, 'thickness': 8.5, 'diameter_id': 12},
            {'id': 72, 'thickness': 9.5, 'diameter_id': 12},
            {'id': 73, 'thickness': 11.0, 'diameter_id': 12},
            {'id': 74, 'thickness': 12.4, 'diameter_id': 12},
            {'id': 75, 'thickness': 14.0, 'diameter_id': 12},

        # Diameter 340
            {'id': 76, 'thickness': 8.4, 'diameter_id': 13},
            {'id': 77, 'thickness': 9.7, 'diameter_id': 13},
            {'id': 78, 'thickness': 10.9, 'diameter_id': 13},
            {'id': 79, 'thickness': 12.2, 'diameter_id': 13},
            {'id': 80, 'thickness': 13.1, 'diameter_id': 13},
            {'id': 81, 'thickness': 14.0, 'diameter_id': 13},
            {'id': 82, 'thickness': 15.4, 'diameter_id': 13},

        # Diameter 351
            {'id': 83, 'thickness': 9.0, 'diameter_id': 14},
            {'id': 84, 'thickness': 10.0, 'diameter_id': 14},
            {'id': 85, 'thickness': 11.0, 'diameter_id': 14},
            {'id': 86, 'thickness': 12.0, 'diameter_id': 14},

        # Diameter 377
            {'id': 87, 'thickness': 9.0, 'diameter_id': 15},
            {'id': 88, 'thickness': 10.0, 'diameter_id': 15},
            {'id': 89, 'thickness': 11.0, 'diameter_id': 15},
            {'id': 90, 'thickness': 12.0, 'diameter_id': 15},

        # Diameter 406
            {'id': 91, 'thickness': 9.5, 'diameter_id': 16},
            {'id': 92, 'thickness': 11.1, 'diameter_id': 16},
            {'id': 93, 'thickness': 12.6, 'diameter_id': 16},
            {'id': 94, 'thickness': 16.7, 'diameter_id': 16},

        # Diameter 426
            {'id': 95, 'thickness': 10.0, 'diameter_id': 17},
            {'id': 96, 'thickness': 11.0, 'diameter_id': 17},
            {'id': 97, 'thickness': 12.0, 'diameter_id': 17},

        # Diameter 473
            {'id': 98, 'thickness': 11.1, 'diameter_id': 18},

        # Diameter 508
            {'id': 99, 'thickness': 11.1, 'diameter_id': 19},
            {'id': 100, 'thickness': 12.7, 'diameter_id': 19},
            {'id': 101, 'thickness': 16.1, 'diameter_id': 19}
        ]
    )
# ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM wall_thickness")
    op.execute("DELETE FROM standard_casing_diameter")
