"""add column clearance to casing standard

Revision ID: 8562f9680052
Revises: d17b4122fe21
Create Date: 2026-01-21 15:14:22.736799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8562f9680052'
down_revision: Union[str, Sequence[str], None] = 'd17b4122fe21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_casing_diameter', sa.Column('recommended_clearance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_casing_diameter', 'recommended_clearance')
    # ### end Alembic commands ###
