"""add table construction diameter

Revision ID: ee1a58033dfd
Revises: 14f0ca32b124
Create Date: 2026-01-22 16:06:31.714724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1a58033dfd'
down_revision: Union[str, Sequence[str], None] = '14f0ca32b124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_diameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('column_depth', sa.Float(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_diameter', sa.Float(), nullable=False),
    sa.Column('bit_diameter', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_diameter_id'), 'construction_diameter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_construction_diameter_id'), table_name='construction_diameter')
    op.drop_table('construction_diameter')
    # ### end Alembic commands ###
