"""initial schema clean

Revision ID: f6feb1628d17
Revises: 
Create Date: 2026-01-20 19:13:21.194699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6feb1628d17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wall_thickness',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('thickness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('diameter_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['diameter_id'], ['standard_casing_diameter.id'],
                                            name=op.f('wall_thickness_diameter_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('wall_thickness_pkey'))
                    )
    op.create_table('standard_casing_diameter',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('standard_casing_diameter_pkey'))
                    )
    op.create_table('well',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('well_pkey'))
                    )
    op.create_table('info',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('well_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('pressure_mpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('depth_up_m', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('depth_down_m', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('anomaly_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=False),
                    sa.Column('fracturing_pressure_mpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=False),
                    sa.Column('fracturing_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=False),
                    sa.Column('fracturing_coefficient2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False,
                              nullable=False),
                    sa.Column('mud_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['well_id'], ['well.id'], name=op.f('info_well_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('info_pkey'))
                    )
    op.create_index(op.f('ix_info_id'), 'info', ['id'], unique=False)
    op.create_table('construction',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('well_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('column_depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['well_id'], ['well.id'], name=op.f('construction_well_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('construction_pkey'))
                    )
    op.create_index(op.f('ix_construction_id'), 'construction', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_construction_id'), table_name='construction')
    op.drop_table('construction')
    op.drop_index(op.f('ix_info_id'), table_name='info')
    op.drop_table('info')
    op.drop_table('well')
    op.drop_table('standard_casing_diameter')
    op.drop_table('wall_thickness')
    # ### end Alembic commands ###
